version: '2'

networks:
    app-tier:
        driver: bridge

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    networks:
        - app-tier
    environment:
      - POSTGRESQL_USERNAME=lautaro
      - POSTGRESQL_PASSWORD=genaro
      - POSTGRESQL_POSTGRES_PASSWORD=admin
      - POSTGRESQL_DATABASE=odoo_informe_medico_db
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  odoo:
    image: 'docker.io/bitnami/odoo:13-debian-10'
    networks:
        - app-tier
    ports:
      - '80:8069'
      - '443:8071'
    volumes:
      - 'odoo_data:/bitnami'
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
